### ISSUE TITLE
Sample working on Mono in Linux

### ISSUE THREAD

**Issue by TonyAbell** [petabridge/akkadotnet-code-samples#10]
I have started [here](https://github.com/TonyAbell/akkadotnet-code-samples)

I have started by setting up a FAKE build script.

Also moved from  nuget to paket

**Comment by Aaronontheweb** [comment]
Does the end-user need to have anything installed on their system to use Paket? Or does FAKE download / install it automatically?

**Comment by TonyAbell** [comment]
the fake script download paket automagically

**Comment by TonyAbell** [comment]
I have lighthouse and the web crawler working and talking on mono... next step is getting the Web site working

**Comment by TheAngryByrd** [comment]
:+1:

**Comment by skotzko** [comment]
@TonyAbell any update on this?
