### ISSUE TITLE
Description of the flow of messages...?

### ISSUE THREAD

**Issue by ndsrf** [petabridge/akkadotnet-code-samples#11]
I am trying to follow your example but I am getting a bit lost...

Would it be possible to have a list of what each actor is doing, the normal flow of data between them and the split once the applicaiton is deployed in multiple machines? This is my view (in order, and splitted by tier), not sure if I got everything right:

(WEB)
- SignalRHub: Communication from/to Actor system - website(SignalR)
- CommandProcessor: Communicates the SignalRHub with the remote actors.

(SERVICE)
- RemoteJobActor: It simply passes the messages back and forth between the web & the service. This is instantiated in the cluster.
- ApiMaster: Front end for all the requests from the web clients. Broadcast group just in case more than 1 crawler service is running - only 1 will process a request though.
- DownloadMaster: Another broadcast group to check if a URL has been downloaded or not. Needed just in case we have several services running (broadcast).
- DownloadsTracker: For each URL there will be 1 download master and 1 download tracker in charge of retrieving all the documents inside a URL. The tracker makes sure we don't process a link if the file was already processed.
- CrawlMaster: Main actor for a particular main URL to be processed. It creates a coordinator.
- DownloadCoordinator: Creates ParseWorkers and DownloadWorkers to process requests. Both are organised in a round robin fashion - 10 actors. Coordinates both,
- DownloadWorker: Handles downloads asynchronously, each one can carry up to 50 downloads concurrently, Images are simply listed while HTML documents are sent to ParseWorker for processing.
- ParseWorker: Parses HTML for links and images, for each link it sends a message to the DownloadCoordinator with a request for that link to be processed.

There are quite a lot messages going on between actors which makes it a bit difficult to follow (for me :-() sorry.

My last question: if I wanted to have this distributed in 4 machines: 2 crawlers, 1 lighthouse and 1 web server, what would I need to change? I understand I would need to enter the lighthouse IP address in the other 3 machines, but can I leave the helios.tcp section as it currently is?

Sorry I had this many questions.

By the way when I start 3 or 4 crawler services I start getting errors after a little bit. Is that normal? SOrry some of the error message is in Spanish - it might just be a timeout.

[ERROR][12/05/2015 1:09:54][Thread 0017][[akka://webcrawler/system/transports/ak
kaprotocolmanager.tcp.0/akkaProtocol-tcp%3a%2f%2fwebcrawler%40127.0.0.1%3a12690-
2]] Underlying transport closed.
Cause: Helios.Exceptions.HeliosConnectionException: Se produjo un error durante
el intento de conexión ya que la parte conectada no respondió adecuadamente tras
 un periodo de tiempo, o bien se produjo un error en la conexión establecida ya
que el host conectado no ha podido responder ---> System.Net.Sockets.SocketExcep
tion: Se produjo un error durante el intento de conexión ya que la parte conecta
da no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un er
ror en la conexión establecida ya que el host conectado no ha podido responder
   en System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, So
cketFlags socketFlags)
   en Helios.Net.Connections.TcpConnection.SendInternal(Byte[] buffer, Int32 ind
ex, Int32 length, INode destination)

And after a little while one of the services usually crashes with:
[WARNING][12/05/2015 1:10:34][Thread 0053][remoting] Association to [akka.tcp://
webcrawler@127.0.0.1:12690] having UID [817718607] is irrecoverably failed. UID
is now quarantined and all messages to this UID will be delivered to dead letter
s. Remote actorsystem must be restarted to recover from this situation.

**Comment by varghesep** [comment]
You may try logging the events to the console window so you can see the flow. As I understand what Aaron has used in this example is a divide and conquer approach to process atom feeds. I'm not sure about why you are getting that error.
