### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by varghesep** [petabridge/akkadotnet-code-samples#21]
Shouldn't this read this "Technically, if you sent a list of 100 different feed URLs to the  FeedValidatorActor  then it would create 100 different  FeedValidatorActor  instances to process each feed in parallel."

as

"Technically, if you sent a list of 100 different feed URLs to the  FeedValidatorActor  then it would create 100 different  **FeedCoordinatorActor**  instances to process each feed in parallel."

**Comment by skotzko** [comment]
yes, thank you

**Comment by skotzko** [comment]
thanks for the note. it actually creates instances of the `FeedParserCoordinator`, I'll update that now
