### ISSUE TITLE
DeathWatchNotification at the End of PipeTo example

### ISSUE THREAD

**Issue by mvbaffa** [petabridge/akkadotnet-code-samples#26]
Hi,

I have downloaded the samples and when I run the PipeTo example and the end it shows two Dead Letter messages, it displays:
'Message DeathwatchNotification from akka://MyFirstActorSystem/user/feedValidator/b$ to akka://MyFirstActorSystem/user/feedValidator/b$ was not delivered. 1 dead letters encountered

There two messages. I am new to Akka.Net and could not find where and why this occurs. 

I have included a Context.Watch in FeedValidatorActor to track the FeedParserCoordinator actor, that is created by the Validator, and included a: Receive<Terminated> in the constructor of FeedValidatorActor class and included a sendMessage like this:

Receive<Terminated>(message => SendMessage(string.Format("Validator: {0}.", message));

The Terminated Receive is activated once, as expected, but the two Dead Letter messages are still displayed.

How can I avoid these messages ?

Thanks

**Comment by Aaronontheweb** [comment]
Hi Marcus,

these dead letters are pretty innocuous. A consequence of asynchronous actor shut downs and message deliveries. No need to worry about them - it's safe to ignore these during system shutdown.
