### ISSUE TITLE
The broadcast-group router only sends the message to one matching node.

### ISSUE THREAD

**Issue by creepone** [petabridge/akkadotnet-code-samples#31]
In the WebCrawler sample, the `TrackingService` implements an `ApiMaster` actor that uses a configured `broadcast-group` router to broadcast the `FindRunningJob` message. The configuration looks as follows:

```
deployment {
  /api/broadcaster {
    router = broadcast-group
    routees.paths = ["/user/api"]
    cluster {
      enabled = on
      max-nr-of-instances-per-node = 1
      allow-local-routees = on
      use-role = tracker
    }
}
```

However, when trying in a local setup with multiple instances of the tracking services running as part of the cluster (according to the logs in the Lighthouse, all the nodes have been detected correctly), only one message is ever sent. Also, the counter variable `OutstandingAcknowledgements` that the `ApiMaster` is using to keep track of the number of routees that responded is always set to 1.

I was also able to reproduce the same behavior in a scenario where the `Sender` actor was not part of the routees (as it is in the case of the `ApiMaster`) and tried to remove the `max-nr-of-instances-per-node` setting in my own test project.

Could this be a bug in the router or is there a problem with the configuration ?

**Comment by Aaronontheweb** [comment]
@creepone might be an issue with the way `Group` routers count their routees in Akka.NET - let me double-check on this
