### ISSUE TITLE
Unable to communicate between actors in Cluster

### ISSUE THREAD

**Issue by michaelsync** [petabridge/akkadotnet-code-samples#34]
I am having some problems in communicating between actors in Cluster.

My test project has this structure below. 

**TestJob [C# Console Project]**
- TestJobService.cs
- TestJobActor

**MainProject [C# Console Project]** //Note: I configured this service as a seed node. I didn't use lighthouse. 
- MainService
- JobManagerActor

Note: I don't want to put actors in Shared project or Main project. The actors that are supposed to do a test job should be under "TestJob" project. 

I already followed this article http://getakka.net/docs/clustering/cluster-overview and video. I did enable Akka.Cluster based on the article. I am able to run both  console projects but when I tried to "tell" from JobManagerActor to TestJobActor, it doesn't work. No error but doesn't work. 

I have this config in MainProject. 

             actor {
                   provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
                   deployment {
		        /TestJobAActor {
				router = consistent-hashing-group
                                routees.paths = ["/user/TestJobAActor"]
		                virtual-nodes-factor = 8
				cluster {
				       enabled = on
				       max-nr-of-instances-per-node = 2
				       allow-local-routees = off
				       use-role = backend
				}
		        }							
                     }
             }

Here is the code that I use for sending the message. 

               var backendRouter = Context.ActorOf(Props.Empty.WithRouter(new ClusterRouterGroup(new ConsistentHashingGroup("/user/TestJobAActor"),new ClusterRouterGroupSettings(10, false, "backend", ImmutableHashSet.Create("/user/TestJobAActor")))));
                backendRouter.Tell("Yo yo!");

What am I missing? Thanks in advance. 

Note: My test project with similar structure can be found here https://github.com/michaelsync/APMDemo . (VS2015 project)

One more question: Can we still use the actor selection when using cluster?

                var actorSelection = Context.ActorSelection("akka.tcp://MyBackendProcessingSystem@127.0.0.1:2553/user/BackEndJobAActor"); //This can come from Model
                actorSelection.Tell("Yo yo!");

**Comment by michaelsync** [comment]
It was a stupid error... I fixed it already. Thanks anyway!

**Comment by Caldas** [comment]
What was your error? Can you explain a Little bit?

-----Mensagem Original-----
De: "michaelsync" <notifications@github.com>
Enviada em: ‎26/‎08/‎2015 12:25
Para: "petabridge/akkadotnet-code-samples" <akkadotnet-code-samples@noreply.github.com>
Assunto: Re: [akkadotnet-code-samples] Unable to communicate between actors inCluster (#34)

It was a stupid error... I fixed it already. Thanks anyway!

**Comment by michaelsync** [comment]
I committed the fix code with a bit different file structure in this branch https://github.com/michaelsync/APMDemo/tree/allinoneproject 

There were two issues. 

1. I thought I can sent the string message from one actor to another cross project. I was wrong. It seems like I need to create a custom message class that implemented "IConsistentHashable"  since I am using consistent hash routing. Correct me if I am wrong. 

2. I have to enable the local route (and maybe a few other things) in config. 

Anyways, it's working now. but still one-to-one tho... ( The Actor "BackEndJobCoordinationActor" from JobManager project can send the message to the actor "BackEndJobAActor" from BackEndJobContainer project ) 

Now, I am trying to see if I can make one-to-many actors communication working or not.
