### ISSUE TITLE
PipeTo: & or | for TaskContinuationOptions?

### ISSUE THREAD

**Issue by scottt732** [petabridge/akkadotnet-code-samples#42]
In this doc, https://github.com/petabridge/akkadotnet-code-samples/tree/master/PipeTo there is a section **What are those TaskContinuationOptions.AttachedToParent `&` TaskContinuationOptions.ExecuteSynchronously flags you keep using on ContinueWith inside an actor?**

I stumbed on this commit where the `|` operator is used instead: https://github.com/akkadotnet/akka.net/pull/1383

I _think_ the `|` is correct but I'm rusty w/bit manipulation.

**Comment by thedanny** [comment]
He is right this be | (or) otherwise & will set the value to TaskContinuationOptions.None
