### ISSUE TITLE
Questions about Remote Deployment Sample 

### ISSUE THREAD

**Issue by CleanCoder** [petabridge/akkadotnet-code-samples#43]
I'm new to AKKA.net and wondering what's the remote deployment function provided by Akka. Could you give me some advice. Thanks in advance.

My question is does it support to send a batch of DLLs to the deploy target and dynamically update the original ones to provide new features? 

In the sample, the 'DeployTarget' reference the 'Shared' project. Is it possible to remove this reference and let it still running?
From my understanding, the system works like the 'Deployer' send a message to the target to active an instance of EchoActor, instead of deploy the DLL containing 'EchoActor' to the target.

**Comment by raskolnikoov** [comment]
I also wonder about this. If the DeployTarget needs an reference to Shared it needs to be restarted if the Deployer wants to deploy a new actor.
