### ISSUE TITLE
0 routees

### ISSUE THREAD

**Issue by ramusbucket** [petabridge/akkadotnet-code-samples#45]
I followed steps from "Running the sample" section. It says "0 routees". am I missing anything?

**Comment by chadjefferies** [comment]
I'm experiencing the same issue when trying to run the web crawler example. The WebCrawler UI states 0 routees and the lighthouse service is logging the following error message:

Akka.Remote.EndpointWriter: Dropping message [Akka.Actor.ActorSelectionMessage] for non-local recipient [[akka.tcp://webcrawler@127.0.0.1:4053/]] arriving at [akka.tcp://webcrawler@127.0.0.1:4053] inbound addresses [akka.tcp://lighthouse@127.0.0.1:4053]

**Comment by chadjefferies** [comment]
This is a non-issue. I got too excited and didn't read the entire README. At the bottom is a required config change to the lighthouse service for this example to work.

**Comment by RakeshBabaria** [comment]
cha

> This is a non-issue. I got too excited and didn't read the entire README. At the bottom is a required config change to the lighthouse service for this example to work.

Can you pls be more specific ? Having the same issue
