### ISSUE TITLE
get-dockerip.sh: line 11: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by senzacionale** [petabridge/akkadotnet-code-samples#81]
I am getting this error

get-dockerip.sh: line 11: syntax error: unexpected end of file

**Comment by joonhwan** [comment]
me too

**Comment by senzacionale** [comment]
Check the file. Must be Linux not Windows

**Comment by KiransHub** [comment]
@senzacionale  Sorry but I don't think this explanation is clear enough. 

Are you saying that the containers should be Linux or that the Host operating system should be Linux?

**Comment by senzacionale** [comment]
Important is end of file line. If you are on Linux, then must be end of file Linux formatted and not Windows formatted.
