### ISSUE TITLE
WebCrawler.Service cannot be started - Association failed

### ISSUE THREAD

**Issue by LevanArabuli** [petabridge/akkadotnet-code-samples#9]
![f4gymtg](https://cloud.githubusercontent.com/assets/10230040/7464063/439351f6-f2d0-11e4-8395-20675551bbc3.png)

I tried changing port but it didn't help.

**Comment by TonyAbell** [comment]
I am having the same issue... @Aaronontheweb

**Comment by Aaronontheweb** [comment]
Did you boot up Lighthouse and follow the configuration changes laid out in the README?

**Comment by Aaronontheweb** [comment]
And if you did bootup lighthouse, could you post a screenshot of the status on its end?

**Comment by TonyAbell** [comment]
that worked.. I did not read the readme all the way to the bottom.

**Comment by Aaronontheweb** [comment]
I should probably add  TL;DR; thing to the top :p

**Comment by LevanArabuli** [comment]
That worked, thanks @Aaronontheweb
