### ISSUE TITLE
Modernizing Akka.NET Examples

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akkadotnet-code-samples#94]
Per some of the feedback we received during the 2022 Akka.NET User Survey, we are investing in building more end-to-end samples that follow the "Pit of Success" paradigm - these samples don't feature complex business domains, but they will demonstrate how to correctly leverage Akka.NET infrastructure in a variety of combinations and fashions.

This includes:

* Various features of Akka.NET itself;
* Integrating with other popular 3rd party technologies; and
* Deployment models for popular environments, such as Kubernetes / AWS / Azure.

If you have a specific sample you would like to see addressed, [please file a new issue](https://github.com/petabridge/akkadotnet-code-samples/issues/new)!

**Comment by CumpsD** [comment]
Perhaps make a variation on `Akka.Cluster.Sharding` which also does away with the remark:

> N.B. while this application uses event-sourcing heavily, it does not use CQRS. One CQRS modification you would likely find in a production system is that the ProductIndexActor would very likely be changed to insert all of the relevant product index data into rows in a SQL table as a materialized view, rather than handle queries directly from the Web UI. The / route would likely query that data directly form that materialized table in SQL Server instead so that way the developer wouldn't have to re-invent (in Akka.NET) pagination and other niceties that are mostly built-into or built-on-top-of SQL tooling.

Then one would have an example of that as well?

**Comment by Aaronontheweb** [comment]
@CumpsD I'd be open to modifying that sample to do it!

**Comment by CumpsD** [comment]
> @CumpsD I'd be open to modifying that sample to do it!

What's the preferred way to contact you guys to talk about it? Slack? Discord? ....

**Comment by Aaronontheweb** [comment]
Good question - for now I guess the main Akka.NET Gitter Chat works fine: https://gitter.im/akkadotnet/akka.net

**Comment by Aaronontheweb** [comment]
Starting work on my RabbitMQ sample here: https://github.com/petabridge/akkadotnet-code-samples/pull/98

**Comment by Aaronontheweb** [comment]
This has largely been accomplished.
